apiVersion: 1

datasources:
  - name: BrainHealth MariaDB
    uid: brainhealth-mariadb
    type: mysql
    access: proxy
    url: db:3306
    user: root
    secureJsonData:
      password: ${MYSQL_ROOT_PASSWORD}
    jsonData:
      database: ${MYSQL_DATABASE}
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    isDefault: true
    editable: true
